### ISSUE TITLE
Add support for VS 2019

### ISSUE THREAD

**Issue by etiennemargraff** [jwendl/nord-vs-theme#13]
Thanks for the work on the theme!

Support for VS2019 would be great!

**Comment by jwendl** [comment]
@meulta - this was fixed. Use the vsix in the release for 2019

https://github.com/jwendl/nord-vs-theme/releases/download/v0.0.6/NordTheme.VisualStudio2019.vsix

**Comment by jwendl** [comment]
Re-opening to fix bug.

**Comment by jwendl** [comment]
Ok now it's fixed 😄 

https://github.com/jwendl/nord-vs-theme/releases/tag/v0.0.7
