### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by ShiZNizZLe** [jwendl/nord-vs-theme#17]
Hi,

when i try to compile the solution i get this error. Can't seem to work it out, any idea?

(text in dutch says: "can not load ...... or one of the dependencies. Manifestation of the found assembly doesn't resemble the assembly-reference.)

1>  Kan bestand of assembly Microsoft.VisualStudio.PkgDef, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)
1>C:\Users\Koen\.nuget\packages\microsoft.visualstudio.vsixcolorcompiler\17.0.31410.258\build\Microsoft.VisualStudio.VsixColorCompiler.targets(47,5): error MSB3073: The command ""C:\Users\Koen\.nuget\packages\microsoft.visualstudio.vsixcolorcompiler\17.0.31410.258\build\\..\VsixColorCompiler.exe" "C:\Users\Koen\Desktop\nord-vs-theme-main\src.2022\NordTheme\Nord.vstheme" "bin\Release\Nord.pkgdef" /registerTheme" exited with code 13.

**Comment by jwendl** [comment]
Hello - and thank you for letting us know.

It was because there were some out dated nuget packages that were referencing packages that don't exist anymore.

This has been fixed in the latest push to main branch (at least the [build](https://github.com/jwendl/nord-vs-theme/actions/runs/1664605464) passes). Let us know if that's still not the case.

**Comment by ShiZNizZLe** [comment]
it worked, i only notice that the colors of the various words is not that different, is there some way to make it more colourfull so to say? 
![afbeelding](https://user-images.githubusercontent.com/15122459/150117333-66d6b0db-3bde-494e-8ce3-693214ef6fa9.png)

**Comment by jwendl** [comment]
Yeah it should be more colorful. Looks like we haven't implemented VB.NET yet. I will start working on that soon. It may take a while - thank you for your patience.

**Comment by ShiZNizZLe** [comment]
nice! will see it coming ;)
